### ISSUE TITLE
Idea: #dueDate as Branch Prefix

### ISSUE THREAD

**Issue by marco10x15** [BeatLink/trilium-agenda#1]
I'm learnig to use Trilium and your script is very useful.
Not a JavaScript expert but I think that can be possible, when cloning one  of the:

- Overdue
- This Week
- This Month
- This Year
- Future

add the Branch Prefix using the #dueDate=2023-10-30 value but in the form: "30-10-2023"

Of course for Today this is not worth...

Thanks.

**Comment by BeatLink** [comment]
Good idea, I've been thinking of something similar. 

But wouldn't yyyy-mm-dd be better as a branch prefix? It allows for sorting by chronological order.

**Comment by marco10x15** [comment]
I was thinking that the form: "DD-MM-YYYY" is more human readable and the sorting can be done using #sorted=dueDate.

**Comment by BeatLink** [comment]
Just pushed version 2.0 with this fix. To customize each interval, modify the line that says 

`dueDateString = dueDate.format("...")`

Use this link to guide you
https://day.js.org/docs/en/display/format
