### ISSUE TITLE
bug: Not all notes are cloned

### ISSUE THREAD

**Issue by marco10x15** [BeatLink/trilium-agenda#2]
Working with the script I have found that a lot of notes with the #dueDate are non cloned.

First, I have double checked the Note Id, to ensure the proper corispondance between Note an Note Description

In my scenario only 4 of 6 note with a dueDate in June 2023 are cloned BUT are cloned to This Year

And in the Future note there is no clone and I have two note with a dueDate in the 2024 (#dueDate=2024-10-04 and #dueDate=2024-02-28).

**Comment by marco10x15** [comment]
Found my mistake, the copy and pasting of the note ID inserted a strange and hidden character.

Solved.

**Comment by BeatLink** [comment]
All good :)
